[package]
name = "Project_Debugg"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version =  "0.26.0", features = ["ptrace"] }
gimli = { version = "0.29.0" , features = ["read"] }
fallible-iterator = "0.3.0" 